development:
  adapter: postgresql
  database: bplm_dev
  username:
  password: 
  host: localhost

test:
  adapter: postgresql
  database: bplm_test
  username:
  password: 
  host: localhost

production:
  adapter: postgresql
  database: bplm_prod
  username:
  password: 
  host: localhost